name: Run Daily SIM Check
on:
  schedule:
    - cron: '0 0 * * *' # ירוץ כל יום בחצות
  workflow_dispatch: # מאפשר להריץ ידנית מהכפתור

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run PHP Script
        run: php cron.php
